# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  OMDB_URL=http://www.omdbapi.com
  POPCORN_URL=https://tv-v2.api-fetch.website